# Generated by Django 3.1.1 on 2020-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=50)),
                ('Asunto', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
